# Introduction to NumPy

- NumPy stands for Numerical Python
- It is a Python library used for working with arrays.
- It consists of a multidimensional array of objects and a collection of functions for manipulating them.
- It conducts mathematical and logical operations on arrays.

# What is an array?
<br>
- An array is a central data structure of the NumPy library.<br>
- It is a grid  of homogeneous vlaues (same data type).<br>
- The rank of the array is the number of dimensions.<br>
- The array object in NumPy is called *ndarray.

# Advantages of NumPy

- It provides an array object that is faster than traditional Python lists.
- It provides supportig functions.
- Arrays are frequently used in data science.

In [1]:
# Importing numpy

import numpy as np
arr = np.array([1,2,3,4,5])  # Creating an ndarray
arr

array([1, 2, 3, 4, 5])

In [4]:
arr = np.array({1,2,3,4,5}) # Creating an ndarray (dictionary)
arr

array({1, 2, 3, 4, 5}, dtype=object)

In [5]:
arr = np.array((1,2,3,4,5)) # Creating an ndarray (tuple:but in output it is giving list inside tuple)
arr

array([1, 2, 3, 4, 5])

In [6]:
arr = np.array({1:'hello',2:'world'}) # Creating ndarray from dictionary
arr

array({1: 'hello', 2: 'world'}, dtype=object)

In [7]:
arr = np.array([1,'rishi',2,'hello',3]) # using hetrogenous data types 
arr

array(['1', 'rishi', '2', 'hello', '3'], dtype='<U11')

In [8]:
arr = np.array([1,'rishi',2,'hello',3,None]) # using hetrogenous data types with None
arr

array([1, 'rishi', 2, 'hello', 3, None], dtype=object)

In [9]:
arr = np.array([1,'rishi',2,'hello',3,'jhgjh']) # using hetrogenous data types 
arr

array(['1', 'rishi', '2', 'hello', '3', 'jhgjh'], dtype='<U11')

In [10]:
#creating a 1D array

arr = np.array([2,3,4,5,6])
arr

array([2, 3, 4, 5, 6])

In [11]:
#creating a 2D array
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [16]:
#creating a 3D array
arr = np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[11,12,13,14,15],[16,17,18,19,20]],[[21,22,23,24,25],[26,27,28,29,30]]])
arr

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]],

       [[21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30]]])

In [26]:
#creating a 4D array
arr = np.array([[[[1,2,3,4,5],[6,7,8,9,10]],[[11,12,13,14,15],[16,17,18,19,20]],[[21,22,23,24,25],[26,27,28,29,30]]],[[[1,2,3,4,5],[6,7,8,9,10]],[[11,12,13,14,15],[16,17,18,19,20]],[[21,22,23,24,25],[26,27,28,29,30]]]])
arr

array([[[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]],

        [[11, 12, 13, 14, 15],
         [16, 17, 18, 19, 20]],

        [[21, 22, 23, 24, 25],
         [26, 27, 28, 29, 30]]],


       [[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]],

        [[11, 12, 13, 14, 15],
         [16, 17, 18, 19, 20]],

        [[21, 22, 23, 24, 25],
         [26, 27, 28, 29, 30]]]])

In [32]:
#creating a 5D array
arr = np.array([[[[1,2],[3,4]],[[5,6],[7,8]]],[[[1,2],[3,4]],[[5,6],[7,8]]],[[[1,2],[3,4]],[[5,6],[7,8]]],[[[1,2],[3,4]],[[5,6],[7,8]]],[[[1,2],[3,4]],[[5,6],[7,8]]],[[[1,2],[3,4]],[[5,6],[7,8]]],[[[1,2],[3,4]],[[5,6],[7,8]]],[[[1,2],[3,4]],[[5,6],[7,8]]]])
arr

array([[[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]],


       [[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]],


       [[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]],


       [[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]],


       [[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]],


       [[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]],


       [[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]],


       [[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]]])

In [ ]:
#creating 5D array
arr = np.array([[]])

In [34]:
h = np.array(range(10))
h

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
# what could be another way to create an array
y = [1,2,3,4]
x = np.array(y)
x

array([1, 2, 3, 4])

In [18]:
# what could be another way to create an array
x = np.array(range(10))
x.shape


(10,)

In [45]:
# what could be another way to create an array
x = np.array(range(10))
x.ndim # it tells about the dimension of the array which is one here

1

In [46]:
# what could be another way to create an array
x = np.array([[[range(10)]]])
x.ndim # the game is of the bracket. 

4

In [47]:
# we can use arange instead of range. It works same as range
my_arr = np.arange(10)
my_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [51]:
%timeit my_arr2 = my_arr * 2

1.86 ms ± 6.92 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [52]:
%timeit my_list2 = [x*2 for x in my_list]

80.1 ms ± 4.28 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


# Data types

- The bit is the most basic or smallest unit of information in computing 
- The byte is a unit of information which contains 8 bits.
<br>
<br>
In the form of:   1 | 0 | 1 | 1 | 0 | 0 | 0 |1<br>
(bit = any single unit like 1 or 0) and byte is made of 8 bits

# Data types:
<br>
- Byte strings are constrained by the character encoding used. In character encodings like ASCII, each character is represented by a single byte, limiting the available characters to the 128 ASCII CHARACTERS.<br>
<br>
- Unicode strings cover a much larger range of characters, including those from various languages and special symbols.<br>
<br>
- "object" data type is used for all other data types.

# Data types:<br>
# 1. Bytes String
- bytes
- bytes_
- S
- a<br>
<br>
# 2. Unicode strings
- U
- str
- str_
- unicode<br>
<br>
# 3. object
- object
- O

In [5]:
arr = np.array(['hello',1,'world',34.5,True,2j])
arr

array(['hello', '1', 'world', '34.5', 'True', '2j'], dtype='<U64')

In [10]:
import numpy as np

In [14]:
arr = np.array([[[[1,2,3,4]],[[9,10,11,12]]],[[[1,2,3,4]],[[9,10,11,12]]],[[[1,2,3,4]],[[9,10,11,12]]]])
print(arr)
arr.shape

[[[[ 1  2  3  4]]

  [[ 9 10 11 12]]]


 [[[ 1  2  3  4]]

  [[ 9 10 11 12]]]


 [[[ 1  2  3  4]]

  [[ 9 10 11 12]]]]


(3, 2, 1, 4)

In [15]:
arr = np.array([[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]],[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]])
print(arr)
arr.shape

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]

 [[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]]


(2, 3, 5)

In [20]:
arr = np.array([[[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]],[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]]])
print(arr)
arr.shape

[[[[ 1  2  3  4  5]
   [ 6  7  8  9 10]
   [11 12 13 14 15]]

  [[ 1  2  3  4  5]
   [ 6  7  8  9 10]
   [11 12 13 14 15]]]]


(1, 2, 3, 5)

In [21]:
# 1 2 1 4    home work

In [23]:
arr = np.array([[[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]],[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]]])


# Array Inspection 

In [21]:
# .ndim, .shape, .reshape , .size, .dtype 

# Methods and Functions used with ndarrays

In [1]:
import numpy as np

In [2]:
# np.ones(shape,dtype)    --- Return a new array of given shape and type, filled with ones
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [23]:
np.ones((1,5),dtype="U") # converting in string

array([['1', '1', '1', '1', '1']], dtype='<U1')

In [25]:
type(np.ones((1,5)).dtype) # dtype is an object itself

numpy.dtype[float64]

In [26]:
# np.zeros (shpape,dtype)   ----   Return a new array of given shape and type, filled with zeros
np.zeros((1,5,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [27]:
np.zeros((2,5),"S")

array([[b'', b'', b'', b'', b''],
       [b'', b'', b'', b'', b'']], dtype='|S1')

In [14]:
# np.empty (shape,dtype)
# Return a new array of given shape and type, without initializing entries.
np.empty((2,1),"uint")

array([[ 858993460],
       [1076114227]], dtype=uint32)

In [28]:
# np.full  (shape,fill_value,dtype)
# Return a new array of given shape and type, filled with fill_value

np.full((2,2,4),80,"S")

array([[[b'8', b'8', b'8', b'8'],
        [b'8', b'8', b'8', b'8']],

       [[b'8', b'8', b'8', b'8'],
        [b'8', b'8', b'8', b'8']]], dtype='|S1')

In [36]:
# np.full  (shape,fill_value,dtype)
# Return a new array of given shape and type, filled with fill_value

np.full((2,2,4),'rishi')

array([[['rishi', 'rishi', 'rishi', 'rishi'],
        ['rishi', 'rishi', 'rishi', 'rishi']],

       [['rishi', 'rishi', 'rishi', 'rishi'],
        ['rishi', 'rishi', 'rishi', 'rishi']]], dtype='<U5')

In [37]:
np.full((2,2,4),'rishi',dtype="U")

array([[['r', 'r', 'r', 'r'],
        ['r', 'r', 'r', 'r']],

       [['r', 'r', 'r', 'r'],
        ['r', 'r', 'r', 'r']]], dtype='<U1')

In [42]:
# np.arange(start,stop,step,dtype)  -- Return evenly spaced values within a given interval.
np.arange(3,10,2)

array([ 3.5,  5.8,  8.1, 10.4])

In [11]:
# can we use floating point start,stop & step?

np.arange(3.5,10.4,2.2)

# The answer is yes

array([ 3.5,  5.7,  7.9, 10.1])

In [17]:
4.66666667-2   # difference is same

2.6666666699999997

In [19]:
10-7.33333333  # difference is same

2.6666666699999997

In [20]:
# numpy.linspace(start, stop, num=50, endpoint= true,dtype)
# Return evenly spaced numbers over a specified interval.
# what do num=50 and endpoint = True suggest here?
# num=50 is the default value of num when not given , i.e , it will give 50 numbers in the range
# endpoint = True is the default value of endpoint which tells us that the stop value is inclusive by default
np.linspace(2,10,4)

array([ 2.        ,  4.66666667,  7.33333333, 10.        ])

In [21]:
np.linspace(2,10,endpoint=False)

array([2.  , 2.16, 2.32, 2.48, 2.64, 2.8 , 2.96, 3.12, 3.28, 3.44, 3.6 ,
       3.76, 3.92, 4.08, 4.24, 4.4 , 4.56, 4.72, 4.88, 5.04, 5.2 , 5.36,
       5.52, 5.68, 5.84, 6.  , 6.16, 6.32, 6.48, 6.64, 6.8 , 6.96, 7.12,
       7.28, 7.44, 7.6 , 7.76, 7.92, 8.08, 8.24, 8.4 , 8.56, 8.72, 8.88,
       9.04, 9.2 , 9.36, 9.52, 9.68, 9.84])

In [23]:
np.linspace(2,10,endpoint=False).size # to check how many vlaues

50

In [24]:
np.linspace(2,10,endpoint=False).dtype # to check the data type

dtype('float64')

In [22]:
np.linspace(2,10,num=10.2)

TypeError: 'float' object cannot be interpreted as an integer

In [27]:
np.array(np.arange(2,10,3))

array([2, 5, 8])

In [38]:
np.array([1,2,3,4,np.arange(2,10,3)],dtype=object) # array as an element inside array

array([1, 2, 3, 4, array([2, 5, 8])], dtype=object)

In [39]:
np.array([1,2,3,4,np.arange(2,10,3)],dtype='O')

array([1, 2, 3, 4, array([2, 5, 8])], dtype=object)

In [40]:
np.array([1,2,3,4,np.arange(2,10,3)],dtype=str)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (5,) + inhomogeneous part.

# Shape manipulation in NumPy

In [2]:
import numpy as np

In [4]:
# .reshape
x = np.array([1,2,3,4])
print(x)
print(x.shape)
x = x.reshape(2,2) # Create a copy of the ndarray
x

[1 2 3 4]
(4,)


array([[1, 2],
       [3, 4]])

In [3]:
x

array([[1, 2],
       [3, 4]])

In [4]:

x.reshape(1,1,2,2,1)

array([[[[[1],
          [2]],

         [[3],
          [4]]]]])

In [5]:
# .flatten() ---- copy of array
x.flatten()

array([1, 2, 3, 4])

In [6]:
# x.ravel() ---- view of array (modification of original array)
x.ravel()

array([1, 2, 3, 4])

In [7]:
x

array([[1, 2],
       [3, 4]])

In [9]:
# .resize()  --  just like .reshape but it changes the value of x but .reshape creates a copy
x.resize(4,1)
x

array([[1],
       [2],
       [3],
       [4]])

In [10]:
x.reshape(2,2)
x

array([[1],
       [2],
       [3],
       [4]])

# Stacking
Joining a sequence of arrays along a new axis.

In [5]:
#stack
#2d
import numpy as np
n1 = np.array([[1,2,4],
               [5,6,7]])
n2 = np.array([[8,9,10],
              [11,12,13]])
print(f'n1 : \n {n1} \nn2 : \n {n2} \n')
print("for axis=0:\n",np.stack((n1,n2),axis=0),"\n") # row-wise stacking

n1 : 
 [[1 2 4]
 [5 6 7]] 
n2 : 
 [[ 8  9 10]
 [11 12 13]] 

for axis=0:
 [[[ 1  2  4]
  [ 5  6  7]]

 [[ 8  9 10]
  [11 12 13]]] 



In [6]:
#stack
#2d
import numpy as np
n1 = np.array([[1,2,4],
               [5,6,7]])
n2 = np.array([[8,9,10],
              [11,12,13]])
print(f'n1 : \n {n1} \nn2 : \n {n2} \n')
print("for axis=1:\n",np.stack((n1,n2),axis=1),"\n") # row-wise stacking

n1 : 
 [[1 2 4]
 [5 6 7]] 
n2 : 
 [[ 8  9 10]
 [11 12 13]] 

for axis=1:
 [[[ 1  2  4]
  [ 8  9 10]]

 [[ 5  6  7]
  [11 12 13]]] 



In [9]:
# stacking of 1d array in o axis
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
print(np.stack((a,b),axis=0))

[[1 2 3 4]
 [5 6 7 8]]


In [10]:
# stacking of 1d array in 1 axis
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
print(np.stack((a,b),axis=1))

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [11]:
# stacking of 1d array in 1 axis
a = np.array([1,2,3,4])
b = np.array([5,6,7])
print(np.stack((a,b),axis=1))

ValueError: all input arrays must have the same shape

In [13]:
# stacking of 1d array in 1 axis
a = np.array([1,2,3,4])
b = np.array([[5,6,7,8],
              [11,12,13,14]])
print(np.stack((a,b),axis=1))

ValueError: all input arrays must have the same shape

In [16]:
# stacking of 1d array in 2 axis
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
print(np.stack((a,b),axis=2))

AxisError: axis 2 is out of bounds for array of dimension 2

# Concatination
join a sequence of arrays along an existing axis.

In [2]:
# 2D array
import numpy as np

x = np.array([[1,2,3],
            [4,5,6]])
y = np.array([[7,8,9],
             [10,11,12]])

print(f'x : \n {x} \ny: \n {y} \n')
print('Resulting array:\n',np.concatenate((x,y),axis=0)) # row-wise concatenation

x : 
 [[1 2 3]
 [4 5 6]] 
y: 
 [[ 7  8  9]
 [10 11 12]] 

Resulting array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [3]:
print(f'x : \n {x} \ny: \n {y} \n')
print('Resulting array:\n',np.concatenate((x,y),axis=0)) # column-wise concatenation

x : 
 [[1 2 3]
 [4 5 6]] 
y: 
 [[ 7  8  9]
 [10 11 12]] 

Resulting array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [6]:
# 1D

n1 = np.array([1,2,3,4])
n2 = np.array([5,6,7,8])
print(f'n1 : \n {n1} \nn2: \n {n2} \n')
print('for axis=0:\n',np.concatenate((n1,n2),axis=0),'\n')

n1 : 
 [1 2 3 4] 
n2: 
 [5 6 7 8] 

for axis=0:
 [1 2 3 4 5 6 7 8] 



In [8]:
# 1D

n1 = np.array([1,2,3,4])
n2 = np.array([5,6,7,8])
print(f'n1 : \n {n1} \nn2: \n {n2} \n')
print('for axis=0:\n',np.concatenate((n1,n2),axis=1),'\n') # 1D array cannot be in axis 1

n1 : 
 [1 2 3 4] 
n2: 
 [5 6 7 8] 



AxisError: axis 1 is out of bounds for array of dimension 1

# hstack and vstack
hstack is horizontal<br>
vstack is vertical<br>
<br>
For 2D --- concatenate ---- hstack ---- axis=1<br>
For 2D --- concatenate ---- vstack ---- axis=0<br>
<br>
For 1D --- concatenate ---- hstack ---- axis=0<br>
For 1D ---    stack    ---- vstack ---- axis=0

In [9]:
# 1D

n1 = np.array([1,2,3,4])
n2 = np.array([5,6,7,8])

In [10]:
np.hstack((n1,n2)) # np.concatenate((n1,n2),axis=0)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [12]:
np.vstack((n1,n2))  # np.stack((n1,n2),axis=0)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

# Indexing, Slicing & Striding 

In [13]:
# 1D
# (AXIS 0,)
# (COLUMNS,)
# (0D)
x = np.array([1,2,3,4])
print(x[3])
print(x[0])   # It is same as list in 1D array

4
1


In [14]:
# 2D
# (AXIS 0,AXIS 1)
# (ROWS, COLUMNS)
# (1D, 0D)
x= np.array([[1,2,3,4],
            [5,6,7,8]])
x[0,1] # preferred way

2

In [15]:
x[0][1] # alternative way

2

In [17]:
x[-1,-2]

7

In [18]:
x[-2,-3]

2

In [5]:
# indexing in 3d array
# (Axis 0, Axis 1, Axis 2)
# (2D,1D,0D)
import numpy as np

x = np.array([[[1,2,3,4],
              [5,6,7,8]],
             [[9,10,11,12],
             [13,14,15,16]]])
print(x[0])
print(x[1])

[[1 2 3 4]
 [5 6 7 8]]
[[ 9 10 11 12]
 [13 14 15 16]]


In [6]:
x[1,0,3]

12

In [7]:
x[0,0]

array([1, 2, 3, 4])

In [8]:
x[0,1,3]

8

In [9]:
x[1,0,3]

12

# Slicing & Striding
start(inclusive):stop(exclusive):step

In [12]:
# 1D
x = np.array([1,2,3,4])
x[0:4:2]

array([1, 3])

In [13]:
x[::2]

array([1, 3])

In [14]:
# slicing in 2D
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
a[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [15]:
a[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
a[0:2,0]

array([1, 4])

In [17]:
a[0,1:3]

array([2, 3])

# Arithmetic with NumPy
- Any operation between equal-size arrays happens element-wise.

In [18]:
import numpy as np
a = np.array([[1,2,3],
             [4,5,6]])
b = np.array([[2,3,4],
             [5,6,7]])

a+b

array([[ 3,  5,  7],
       [ 9, 11, 13]])

In [19]:
a*b

array([[ 2,  6, 12],
       [20, 30, 42]])

In [20]:
a-b

array([[-1, -1, -1],
       [-1, -1, -1]])

In [21]:
a/b

array([[0.5       , 0.66666667, 0.75      ],
       [0.8       , 0.83333333, 0.85714286]])

In [22]:
a//b

array([[0, 0, 0],
       [0, 0, 0]])

In [23]:
a**b

array([[     1,      8,     81],
       [  1024,  15625, 279936]])

In [24]:
a%b

array([[1, 2, 3],
       [4, 5, 6]])

# Arithmatic operations with scalars propagate the scalar argument to each element in the array 
- Operations between differently sized arrays is called broadcasting

In [25]:
a*2   # Broascasting

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [26]:
a-2

array([[-1,  0,  1],
       [ 2,  3,  4]])

In [27]:
a-np.array([2])

array([[-1,  0,  1],
       [ 2,  3,  4]])

In [28]:
a+1+3+4

array([[ 9, 10, 11],
       [12, 13, 14]])

# Universal Functions
- A universal function, or ufunc, is a function that perform element-wise operations on data in ndarrays.

In [30]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
np.add(a,b)

array([ 6,  8, 10, 12])

In [32]:
np.subtract(a,b)

array([-4, -4, -4, -4])

In [33]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [35]:
import numpy

In [36]:
dir(numpy)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__packag

# Pseudo-Random Number Generation 

In [38]:
# In python we have a built in module random
import random
random.random()

0.6333413973673455

In [40]:
random.seed(2)   # same seed vaue will generate the same random no.
random.random()

0.9560342718892494

In [10]:
import numpy as np
np.random.seed(1)
np.random.random()

0.417022004702574

# Boolean array

In [6]:
import numpy as np
names = np.array(['rohit','priyanshu','gaurav','rohit','rishi'])

In [12]:
names == 'rohit' # this gives a boolean array

array([ True, False, False,  True, False])

In [13]:
names[names=='rohit'] # ulike panda here index value is not attached. index value has changed

array(['rohit', 'rohit'], dtype='<U9')

In [20]:
arr1 = np.array([['hello','world'],['xyz']])
arr1
# shape shoul also be homogenous

C:\Users\sageo\AppData\Local\Temp\ipykernel_18996\2793371676.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr1 = np.array([['hello','world'],['xyz']])


array([list(['hello', 'world']), list(['xyz'])], dtype=object)

In [12]:
arr = np.array([[[[1,2]],
                [[3,4]]],
                [[[5,6]],
                [[7,8]]]])
arr.shape

(2, 2, 1, 2)