In [77]:
import numpy as np

In [95]:
# Ans.5
lst = ["array","numpy"]
vow = ['a','e','i','o','u']
for i in lst:
    for j in vow:
        if j in i and i.count(j)>1:

array
numpy


In [88]:
rev1 = np.array([[1,2,3,4],[5,6,7,8]])
rev1[0]=rev1[0][::-1]
rev1[1]=rev1[1][::-1]
rev1

array([[4, 3, 2, 1],
       [8, 7, 6, 5]])

In [83]:
nd = np.array([1,2,3,4,5,6,7,8,9])
ndr = []
for i in nd:
    if i>2 and i<8:
        ndr.append(i)
a = np.array(ndr)
a

array([3, 4, 5, 6, 7])

In [87]:
nd = np.array([1,2,3,4,5,6,7,8,9])
a = np.array([i for i in nd if i>2 and i <8])
a

array([3, 4, 5, 6, 7])

In [15]:
nd = np.array([1,2,3,4,5,6,7,8,9])
nd[(nd>=4) & (nd<=7)] # performs logical AND element wise

array([4, 5, 6, 7])

In [16]:
nd[nd>4]

array([5, 6, 7, 8, 9])

In [18]:
nd>=4

array([False, False, False,  True,  True,  True,  True,  True,  True])

In [20]:
nd[nd>4 and nd<=8]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [77]:
lt = [1,2,3,45]
a = np.array(lt)
a

array([ 1,  2,  3, 45])

home solutions

In [80]:
lst = ['hello','array','lets','numpey','wht']
vow = ['a','e','i','o','u']
nlst = []
for i in lst:
    for j in i:
        for k in vow:
            if j==k:
                nlst.append(i)
for i in nlst:
    if nlst.count(i)==1:
        nlst.remove(i)
        print(set(nlst))   

{'array', 'hello', 'numpey'}


In [1]:
# class solution
lst = ['hello','world','python','data science']
vowel_words=[]
for x in lst:
    count=0
    for i in 'aeiouAEIOU':
        count+=1
    if count>=2:
        vowel_words.append(x)
print(vowel_words)

['hello', 'world', 'python', 'data science']


In [26]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])
arr = arr[[1,0]]
arr

array([[5, 6, 7, 8],
       [1, 2, 3, 4]])

In [59]:
arr = np.array([[1,2],[5,6]])
print(arr)
arr[0]=arr[0][::-1]
arr[1]=arr[1][::-1]
arr

[[1 2]
 [5 6]]


array([[2, 1],
       [6, 5]])

# class solution

In [4]:
# swap two columns in a 2d numpy array 
import numpy as np

In [5]:
x = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])

x[:,[0,1]] = x[:,[1,0]]
x

array([[2, 1, 3],
       [5, 4, 6],
       [8, 7, 9]])

In [9]:
# swap two rows in a 2d array
x = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])

x[[1,2]] = x [[2,1]]
x

6

In [11]:
# reverse all the rows of a 2d ndarray
x = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])

x = x[:,::-1]
x

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

In [13]:
# reverse all the rows of a 2d ndarray
x = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])

x[:]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])